esphome:
  name: ledcontrol-camera-ale
  friendly_name: LedControl Camera Ale
  platformio_options:
    upload_speed: 230400
  includes:
    - "CustomComponents/Sensors/ens160.h"
  libraries:
    - SPI
    - Wire
    - "dfrobot/DFRobot_ENS160@^1.0.1"
    - "dvarrel/AHT20@^1.0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CwFrFvl39XhPbZR+dL6O57Wf8FbnhB+RLFuCuthW20o="

ota:
  password: "d5c40d5d53af2a826f858cb96764f255"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ledcontrol-Camera-Ale"
    password: "1amEx0udo6rj"

captive_portal:
    
# Example configuration entry for ESP32
i2c:
  sda: 21
  scl: 22
  scan: true

output:
  - platform: ledc
    pin: 32
    id: LED_PIN

light:
  - platform: monochromatic
    output: LED_PIN
    name: "Led 1 scrivania"

sensor:
  - platform: bmp280
    temperature:
      name: "Temperatura"
    pressure:
      name: "Pressure"
    address: 0x76
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
  - platform: custom
    lambda: |-
      auto ens160Sensor = new ENS160Sensor();
      App.register_component(ens160Sensor);
      return {ens160Sensor->aqi_sensor, ens160Sensor->eco2_sensor, ens160Sensor->tvoc_sensor, ens160Sensor->status_sensor, ens160Sensor->temp_sensor, ens160Sensor->hum_sensor};
    sensors:
    - name: "AQI"
      device_class: "aqi"
    - name: "eCO2"
      device_class: "carbon_dioxide"
    - name: "TVOC"
      device_class: "VOLATILE_ORGANIC_COMPOUNDS_PARTS"
    - name: "Status"
      entity_category: "diagnostic"
    - name: "AHTTemperature"
      device_class: "temperature"
    - name: "Humidity"
      device_class: "humidity"